# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: 文档排序

# Attribute name
nameFrom: title

# Model Class name
modelClass: Jc91715\Book\Models\Chapter

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
