# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    showTree:
        label: Tree
        type: switch


    doc:

        # Filter name
        label: 选择文档

        # Model Class name
        modelClass: Jc91715\Book\Models\Doc

        # Model attribute to display for the name
        nameFrom: name

        # Apply query scope
        scope: FilterBooks

    state:
        label: 状态
        type: group
        conditions: state in (:filtered)
        options:
            no_claim: 我要翻译
            translating: 正在翻译中...
            reviewing: 正在审阅中...
            unfinished_translation: 翻译未完成
            finished_translation: 翻译已完成
            re_translating: 正在重译中...
            improving: 正在改进中...


