# ===================================
#  Relation Behavior Config
# ===================================

chapters:
    label: 章节
    view:
        list: $/jc91715/book/models/chapter/columns.yaml
        showSearch: true
        toolbarButtons: create|delete
    manage:
        form: $/jc91715/book/models/chapter/fields.yaml
        recordsPerPage: 10
