# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Section

# Model Form Field configuration
form: $/jc91715/book/models/section/fields.yaml

# Model Class name
modelClass: Jc91715\Book\Models\Section

# Default redirect location
defaultRedirect: jc91715/book/sections

# Create page
create:
    title: Create Section
    redirect: jc91715/book/sections/update/:id
    redirectClose: jc91715/book/sections

# Update page
update:
    title: Edit Section
    redirect: jc91715/book/sections
    redirectClose: jc91715/book/sections

# Preview page
preview:
    title: Preview Section
